class ReactionVisualizer {
  constructor(){this.svg=document.querySelector('#reactionSvg');this.select=document.querySelector('#reactionSelect');this.title=document.querySelector('#stepTitle');this.text=document.querySelector('#stepText');this.badge=document.querySelector('#stepBadge');this.mech=document.querySelector('#mechanismText');this.rate=document.querySelector('#rateLaw');this.timeline=document.querySelector('#timeline');this.whyBtn=document.querySelector('#whyBtn');this.whyText=document.querySelector('#whyText');this.step=0;this.timer=null;this.delay=1200;this.bind();this.load(this.select.value)}
  bind(){document.querySelector('#prevBtn').onclick=()=>this.prev();document.querySelector('#nextBtn').onclick=()=>this.next();document.querySelector('#resetBtn').onclick=()=>this.reset();document.querySelector('#playBtn').onclick=()=>this.toggle();this.select.onchange=()=>this.load(this.select.value);document.querySelector('#speedSelect').onchange=e=>this.delay=+e.target.value;this.whyBtn.onclick=()=>{this.whyText.hidden=!this.whyText.hidden;this.whyBtn.querySelector('span').textContent=this.whyText.hidden?'+':'−'};document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')this.next();if(e.key==='ArrowLeft')this.prev();if(e.code==='Space'){e.preventDefault();this.toggle()}})}
  get reaction(){return REACTIONS[this.select.value]}
  load(id){this.select.value=id;this.step=0;this.stop();this.rate.textContent=this.reaction.rateLaw;document.querySelector('.hero h1').textContent=this.reaction.title;document.querySelector('.hero p').textContent=this.reaction.subtitle;document.querySelector('#concept1').textContent=this.reaction.concepts[0];document.querySelector('#concept2').textContent=this.reaction.concepts[1];document.querySelector('#concept3').textContent=this.reaction.concepts[2];this.buildTimeline();this.render()}
  buildTimeline(){this.timeline.innerHTML='';this.reaction.steps.forEach((s,i)=>{const b=document.createElement('button');b.className='time-dot';b.innerHTML=`<span>${i+1}</span><small>${s.title}</small>`;b.onclick=()=>{this.step=i;this.render()};this.timeline.appendChild(b)})}
  render(){const s=this.reaction.steps[this.step];this.badge.textContent=`STEP ${this.step+1} / ${this.reaction.steps.length}`;this.title.textContent=s.title;this.text.textContent=s.text;this.mech.textContent=s.mechanism;this.whyText.textContent=s.why;this.whyText.hidden=true;this.whyBtn.querySelector('span').textContent='+';[...this.timeline.children].forEach((x,i)=>x.classList.toggle('active',i===this.step));this.draw(s.type)}
  draw(type){this.svg.innerHTML=`<defs><marker id="arrow" markerWidth="12" markerHeight="12" refX="9" refY="4" orient="auto"><path d="M0,0 L10,4 L0,8 Z" fill="currentColor"/></marker><filter id="glow"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>`;const isSN1=this.select.value==='sn1';if(isSN1)this.drawSN1(type);else this.drawSN2(type)}
  atom(x,y,label,cls='') {return `<g class="atom ${cls}"><circle cx="${x}" cy="${y}" r="25"/><text x="${x}" y="${y+7}" text-anchor="middle">${label}</text></g>`}
  bond(x1,y1,x2,y2,cls=''){return `<line class="bond ${cls}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`}
  drawSN1(type){let html=`<text class="molecule-label" x="70" y="55">tert-Butyl bromide</text>`;html+=this.atom(280,230,'C','carbon');html+=this.atom(190,150,'C');html+=this.atom(190,310,'C');html+=this.atom(370,230,'C');html+=this.bond(260,215,210,165)+this.bond(260,245,210,295)+this.bond(300,230,345,230);if(type==='reactants'||type==='ionization'){html+=this.atom(430,230,'Br','halogen');html+=this.bond(395,230,405,230,type==='ionization'?'breaking':'');}else {html+=this.atom(560,230,'C','carbocation');html+=`<text class="charge" x="588" y="205">+</text>`;html+=this.atom(820,230,'Br','halogen');html+=`<text class="charge" x="848" y="205">−</text>`;}
    if(type==='reactants'){html+=this.atom(690,340,'O','oxygen');html+=`<text class="water-label" x="690" y="390">H₂O</text>`}
    if(type==='ionization'){html+=`<path class="electron-arrow" d="M395 205 Q420 145 440 205" marker-end="url(#arrow)"/>`;html+=`<text class="arrow-label" x="415" y="135">bonding e⁻ pair → Br</text>`;}
    if(type==='attack'){html+=this.atom(800,340,'O','oxygen');html+=this.atom(850,390,'H','hydrogen');html+=`<text class="charge" x="830" y="315">+</text>`;html+=this.bond(585,230,775,325,'forming');html+=`<path class="electron-arrow" d="M785 320 Q690 240 590 235" marker-end="url(#arrow)"/>`;html+=`<text class="arrow-label" x="675" y="220">O lone pair → C⁺</text>`;}
    if(type==='product'){html+=this.atom(720,230,'O','oxygen');html+=this.bond(585,230,695,230,'forming');html+=this.atom(780,300,'H','hydrogen');html+=this.bond(735,250,765,280);html+=`<text class="product-label" x="690" y="365">tert-Butanol</text>`;}
    this.svg.innerHTML+=html}
  drawSN2(type){let html=`<text class="molecule-label" x="80" y="70">Bromoethane</text>`;html+=this.atom(320,250,'C','carbon');html+=this.atom(450,250,'C');html+=this.bond(345,250,425,250);html+=this.atom(500,250,'Br','halogen');html+=this.bond(475,250,480,250,type==='attack'||type==='transition'?'breaking':'');if(type==='reactants'){html+=this.atom(720,250,'O','oxygen');html+=`<text class="charge" x="748" y="225">−</text>`;html+=`<text class="water-label" x="700" y="310">OH⁻</text>`}else {html+=this.atom(700,250,'O','oxygen');html+=this.bond(345,250,675,250,'forming');html+=this.atom(850,250,'Br','halogen');html+=`<text class="charge" x="878" y="225">−</text>`;}
    if(type==='attack'||type==='transition'){html+=`<path class="electron-arrow" d="M720 220 Q560 100 350 225" marker-end="url(#arrow)"/>`;html+=`<text class="arrow-label" x="500" y="115">backside nucleophilic attack</text>`;html+=`<path class="electron-arrow secondary" d="M470 225 Q510 170 535 225" marker-end="url(#arrow)"/>`;}
    if(type==='product')html+=`<text class="product-label" x="650" y="330">Ethanol + Br⁻</text>`;this.svg.innerHTML+=html}
  next(){if(this.step<this.reaction.steps.length-1){this.step++;this.render()}else this.stop()}
  prev(){this.step=Math.max(0,this.step-1);this.render()}
  reset(){this.stop();this.step=0;this.render()}
  toggle(){this.timer?this.stop():this.play()}
  play(){document.querySelector('#playBtn').textContent='⏸ Pause';this.timer=setInterval(()=>this.next(),this.delay)}
  stop(){clearInterval(this.timer);this.timer=null;document.querySelector('#playBtn').textContent='▶ Play'}
}
new ReactionVisualizer();
